version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./:/app
      - /app/node_modules
    command: pnpm start:debug
  db:
    image: mysql:latest
    environment:
            - MYSQL_ROOT_USER=root
            - MYSQL_ROOT_PASSWORD=password
    ports:
        - '${DB_PORT}:3306'
    volumes:
        - school-db:/var/lib/mysql
volumes: 
  school-db:
    name: school-db